<a href="https://colab.research.google.com/github/hariThorve/machineLearningJourney/blob/main/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2>Numpy = Numerical Python</h2> <br>

1.Allows several mathematical operations. <br>
2.Faster operations

In [3]:
import numpy as np

#list
list1 = [1, 2, 3, 4, 5]
print(list1)
print(type(list1))

#numpy array

array = np.array([1, 2, 3, 4, 5])
print(array)
print(type(array))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#creating a 2d array in numpy

array2 = np.array([(1, 2, 3), (4, 5, 6)])
print(array2)
array2.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [6]:
#slicing in numpy
array2[1:2]

array([[4, 5, 6]])