<a href="https://colab.research.google.com/github/hariThorve/machineLearningJourney/blob/main/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2>Numpy = Numerical Python</h2> <br>

1.Allows several mathematical operations. <br>
2.Faster operations

In [3]:
import numpy as np

#list
list1 = [1, 2, 3, 4, 5]
print(list1)
print(type(list1))

#numpy array

array = np.array([1, 2, 3, 4, 5])
print(array)
print(type(array))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [22]:
#creating a 2d array in numpy

array2 = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(array2)
array2.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [23]:
#slicing in numpy
array2[1:2]

array([[4, 5, 6]])

In [24]:
# printing a specific element
#the element 6 is present at row 1 and column 2, Remember the counting starts from 0.
print(array2[1, 2])

6


In [25]:
#to check the dimensions of the given array
#1. ndim() function
# The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

array2.ndim

2

In [26]:
#number of total elements in an array is found out by size() function

array2.size

9

In [28]:
#You can create an array with a range of elements:

array3 = np.arange(4)
array3

array([0, 1, 2, 3])

In [31]:
# And even an array that contains a range of evenly spaced intervals. To do this,
# you will specify the first number, last number, and the step size.
array4 = np.arange(2, 9, 2)
array4


array([2, 4, 6, 8])

In [35]:
# sorting an array
array5 = np.array([5, 2, 1, 6, 3, 7, 8])
print(f"Before sorting : {array5}")
print(f"After sorting : {np.sort(array5)}")

Before sorting : [5 2 1 6 3 7 8]
After sorting : [1 2 3 5 6 7 8]


In [39]:
# Concatenation of two arrays

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

c = np.concatenate((a, b))


#concatenating 2d arrays

a1 = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
b1 = np.array([(9, 10, 11, 12), (13, 14, 15, 16)])

np.concatenate((a1, b1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])